//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importadora.ServicioImportacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOImportacion", Namespace="http://schemas.datacontract.org/2004/07/WcfImportacion")]
    [System.SerializableAttribute()]
    public partial class DTOImportacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadUnidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadUnidades {
            get {
                return this.CantidadUnidadesField;
            }
            set {
                if ((this.CantidadUnidadesField.Equals(value) != true)) {
                    this.CantidadUnidadesField = value;
                    this.RaisePropertyChanged("CantidadUnidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImportacion.IServicioImportacion")]
    public interface IServicioImportacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/AltaImportacion", ReplyAction="http://tempuri.org/IServicioImportacion/AltaImportacionResponse")]
        bool AltaImportacion(Importadora.ServicioImportacion.DTOImportacion dtoImp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/AltaImportacion", ReplyAction="http://tempuri.org/IServicioImportacion/AltaImportacionResponse")]
        System.Threading.Tasks.Task<bool> AltaImportacionAsync(Importadora.ServicioImportacion.DTOImportacion dtoImp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioImportacionChannel : Importadora.ServicioImportacion.IServicioImportacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioImportacionClient : System.ServiceModel.ClientBase<Importadora.ServicioImportacion.IServicioImportacion>, Importadora.ServicioImportacion.IServicioImportacion {
        
        public ServicioImportacionClient() {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImportacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AltaImportacion(Importadora.ServicioImportacion.DTOImportacion dtoImp) {
            return base.Channel.AltaImportacion(dtoImp);
        }
        
        public System.Threading.Tasks.Task<bool> AltaImportacionAsync(Importadora.ServicioImportacion.DTOImportacion dtoImp) {
            return base.Channel.AltaImportacionAsync(dtoImp);
        }
    }
}
